version: "3.7"

services:
  db:
    container_name: bookstore-db-prod

  redis:
    container_name: bookstore-redis-prod

  app:
    container_name: bookstore-app-prod
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${BOOKSTORE_SERVER_PORT}:${BOOKSTORE_SERVER_PORT}
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis

  swagger:
    image: swaggerapi/swagger-ui
    container_name: bookstore-swagger-prod
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./api/restful/openapi.yaml:/api.yaml
    environment:
      - SWAGGER_JSON=/api.yaml
