version: "3.7"

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${LIBRARY_DB_PASSWORD}
      MARIADB_DATABASE: ${LIBRARY_DB_DATABASE}
      MARIADB_USER: ${LIBRARY_DB_USERNAME}
      MARIADB_PASSWORD: ${LIBRARY_DB_PASSWORD}
      TZ: ${LIBRARY_SERVER_TIMEZONE}
    expose:
      - ${LIBRARY_DB_PORT}

  redis:
    image: redis:latest
    restart: always
    environment:
      TZ: ${LIBRARY_SERVER_TIMEZONE}
    expose:
      - ${LIBRARY_REDIS_PORT}
