version: "3.7"

services:
  db:
    container_name: library-db-stage
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    container_name: library-redis-stage
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3

  app:
    container_name: library-app-stage
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - ${LIBRARY_SERVER_PORT}:${LIBRARY_SERVER_PORT}
    environment:
      # Override the environment variables in .env.stage
      - LIBRARY_DB_HOST=db
      - LIBRARY_REDIS_HOST=redis
      - TZ=${LIBRARY_SERVER_TIMEZONE}
    env_file:
      - $PWD/.env.stage
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  swagger:
    image: swaggerapi/swagger-ui
    container_name: library-swagger-stage
    restart: always
    expose:
      - 8080
    volumes:
      - $PWD/api/restful/openapi.yaml:/api.yaml:ro
    environment:
      - SWAGGER_JSON=/api.yaml

  caddy:
    image: caddy:2.7.4-alpine
    container_name: library-caddy-stage
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - TZ=${LIBRARY_SERVER_TIMEZONE}
    env_file:
      - $PWD/.env.stage
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/docker/volumes/caddy/caddy_data:/data:rw
      - $PWD/docker/volumes/caddy/caddy_config:/config:rw
    depends_on:
      - app
